# Generated by Django 4.2.1 on 2023-05-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_bio_profile_birth_profile_contact_inf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nation',
            field=models.CharField(blank=True, choices=[('-', '-'), ('V', 'V'), ('E', 'E')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('-', '-'), ('M', 'M'), ('F', 'F')], max_length=2, null=True),
        ),
    ]
