# Generated by Django 4.2.1 on 2023-06-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_profile_picture_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pub_since',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
