# Generated by Django 4.2.1 on 2023-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_pub_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pub_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
