# Generated by Django 4.2.1 on 2023-05-26 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 26, 12, 21, 26, 614385, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publised_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('approved_com', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2023, 5, 26, 12, 21, 26, 615031, tzinfo=datetime.timezone.utc))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
        ),
    ]
