# Generated by Django 4.2.1 on 2023-05-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='social',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
