# Generated by Django 4.2.1 on 2023-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publised_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='social',
            field=models.CharField(max_length=50),
        ),
    ]
