# Generated by Django 4.2.1 on 2023-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_created_at_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='social',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
