# Generated by Django 4.2.1 on 2023-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_content_alter_post_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publised_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
