# Generated by Django 4.2.1 on 2023-05-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publised_date',
        ),
    ]
