# Generated by Django 4.2.1 on 2023-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_post_publised_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=15),
        ),
    ]
