# Generated by Django 4.2.1 on 2023-05-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
